/**
 * background.js — Service Worker for LinkedIn AI Detector
 *
 * Responsibilities:
 * - Listens for messages from the content script.
 * - Reads the Gemini API key from chrome.storage.local.
 * - Sends the post text to Google Gemini API for AI detection analysis.
 * - Returns the probability score (0-100) back to the content script.
 */

const GEMINI_MODEL = "gemini-3.1-flash-lite-preview";
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

/**
 * Diagnostic function to list all models available for the current API key.
 */
async function listAvailableModels() {
  try {
    const result = await chrome.storage.local.get("geminiApiKey");
    const apiKey = result?.geminiApiKey;
    if (!apiKey) return;

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`);
    const data = await response.json();
    console.log("[LinkedIn AI Detector] Dostępne modele dla Twojego klucza:", data.models?.map(m => m.name.replace("models/", "")) || data);
  } catch (err) {
    console.error("[LinkedIn AI Detector] Błąd podczas pobierania listy modeli:", err);
  }
}

// Run diagnostics on startup
listAvailableModels();

/**
 * System prompt instructing Gemini to act as an AI content detector.
 * The model must return ONLY a number 0-100.
 */
const SYSTEM_PROMPT = `You are an expert AI-generated content detector. Your task is to analyze a given text and estimate the probability (0 to 100) that it was generated by an AI language model (like ChatGPT, Gemini, Claude, etc.).

Consider these signals of AI-generated content:
- Overly polished, generic, or corporate language
- Lack of personal anecdotes or authentic voice
- Excessive use of buzzwords, listicles, or motivational clichés
- Perfect grammar with no colloquialisms or typos
- Formulaic structure (hook → body → call-to-action)
- Vague statements that sound profound but lack substance
- Overuse of emojis in a structured, repetitive pattern
- Hashtag stuffing at the end

Consider these signals of human-written content:
- Unique personal stories or specific details
- Imperfect grammar, slang, or regional expressions
- Unconventional structure or stream-of-consciousness style
- Strong, opinionated voice with genuine emotion
- References to specific people, events, or experiences

You MUST respond with ONLY a single integer between 0 and 100. No text, no explanation, no punctuation — just the number.
0 = definitely human-written, 100 = definitely AI-generated.`;

/**
 * Calls the Google Gemini API with the given post text.
 * @param {string} apiKey - The user's Gemini API key.
 * @param {string} postText - The LinkedIn post text to analyze.
 * @returns {Promise<number>} - AI probability score (0-100).
 */
async function analyzeWithGemini(apiKey, postText) {
  const url = `${GEMINI_API_URL}?key=${apiKey}`;

  const requestBody = {
    contents: [
      {
        role: "user",
        parts: [
          {
            text: `${SYSTEM_PROMPT}\n\nAnalyze the following LinkedIn post and return ONLY a number 0-100 representing the probability it was AI-generated:\n\n---\n${postText}\n---`,
          },
        ],
      },
    ],
    generationConfig: {
      temperature: 0.1,
      maxOutputTokens: 10,
    },
  };

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errorMessage =
        errorData?.error?.message || `HTTP ${response.status}: ${response.statusText}`;
      
      console.error(`[LinkedIn AI Detector] API Error (${response.status}):`, errorData);
      
      if (response.status === 429) {
        throw new Error("Przekroczono limit zapytań (Quota Exceeded). Sprawdź limity w Google AI Studio.");
      }
      
      throw new Error(`Błąd Gemini API: ${errorMessage}`);
    }

    const data = await response.json();

    // Extract the text response from Gemini
    const rawText =
      data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? "";

    // Parse the number from the response
    const score = parseInt(rawText, 10);

    if (isNaN(score) || score < 0 || score > 100) {
      console.warn(
        `[LinkedIn AI Detector] Unexpected Gemini response: "${rawText}"`
      );
      throw new Error(
        `Model zwrócił nieprawidłowy wynik: "${rawText}". Oczekiwano liczby 0-100.`
      );
    }

    return score;
  } catch (err) {
    if (err.name === "TypeError" && err.message === "Failed to fetch") {
      throw new Error("Błąd połączenia. Sprawdź dostęp do internetu i klucz API.");
    }
    throw err;
  }
}

/**
 * Message listener — handles "ANALYZE_POST" requests from content.js
 */
chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type !== "ANALYZE_POST") return false;

  const { postText } = message;

  if (!postText || postText.trim().length === 0) {
    sendResponse({ success: false, error: "Brak tekstu posta do analizy." });
    return false;
  }

  // Async handler — must return true to keep the message channel open
  (async () => {
    try {
      // 1. Read the API key from storage
      const result = await chrome.storage.local.get("geminiApiKey");
      const apiKey = result?.geminiApiKey;

      if (!apiKey) {
        sendResponse({
          success: false,
          error:
            "Brak klucza API. Otwórz popup rozszerzenia i wklej swój klucz Google Gemini.",
        });
        return;
      }

      // 2. Call the Gemini API
      const score = await analyzeWithGemini(apiKey, postText);

      // 3. Return the result
      sendResponse({ success: true, score });
    } catch (err) {
      console.error("[LinkedIn AI Detector] Error:", err);
      sendResponse({
        success: false,
        error: err.message || "Wystąpił nieznany błąd.",
      });
    }
  })();


  // Return true to indicate async response
  return true;
});

console.log("[LinkedIn AI Detector] Service Worker loaded.");
